name: Check-R-Package
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  R-CMD-Check:
    runs-on: ubuntu-latest
    steps:
      - name: "â˜ï¸ checkout repository"
        uses: actions/checkout@master

      - name: "ğŸ”§ Setup R"
        uses: r-lib/actions/setup-r@master

      - name: "ğŸ“¦ Install R Package"
        uses: r-lib/actions/setup-r-dependencies@master

      - name: "âœ… Check R Package"
        uses: r-lib/actions/check-r-package@master
